# Voegt grammatica-uitleg (intro) toe aan A1-lessen in index.html.
# Gebruik: python3 dev/a1_intros.py   (idempotent: lessen die al een intro hebben worden overgeslagen)
import re, sys

def card(title, *paras):
    body = ''.join('<p class="muted">' + p + '</p>' for p in paras)
    return '<h2 class="section-title" style="margin-top:0;">' + title + '</h2>' + body

def ex(*lines):  # voorbeeldzinnen onder elkaar
    return '<br>'.join(lines)

INTROS = {
'a1-u1-l1': card('¡Hola! ¿Qué tal?',
    'Spaans zet bij een vraag of uitroep ook een <b>omgekeerd teken aan het begin</b>: <b>¿</b>...? en <b>¡</b>...!',
    ex('<i>¡Hola!</i> — Hallo!', '<i>¿Qué tal?</i> — Hoe gaat het?'),
    'Let ook op de accenten (á, é, í, ó, ú): <i>adiós</i>, <i>días</i>. Vergeet je ze, dan geeft Pico oranje.'),
'a1-u1-l4': card('Hoe heet je? — llamarse',
    '<i>Llamarse</i> betekent letterlijk "zichzelf noemen". Daarom staat er een klein woordje vóór het werkwoord:',
    ex('<b>me</b> llamo — ik heet', '<b>te</b> llamas — jij heet', '<b>se</b> llama — hij/zij heet, u heet', '<b>nos</b> llamamos — wij heten', '<b>os</b> llamáis — jullie heten', '<b>se</b> llaman — zij heten'),
    'Het onderwerp (yo, tú, él...) laat je meestal weg: aan de werkwoordsvorm zie je al wie het is.'),
'a1-u2-l1': card('El en la — mannelijk en vrouwelijk',
    'Elk zelfstandig naamwoord is mannelijk of vrouwelijk. Mannelijk krijgt <b>el</b>, vrouwelijk krijgt <b>la</b>.',
    'Vuistregel: op <b>-o</b> is meestal mannelijk (<i>el libro</i>), op <b>-a</b> meestal vrouwelijk (<i>la mesa</i>). Er zijn uitzonderingen, leer het lidwoord dus altijd mee.'),
'a1-u2-l2': card('Uitzonderingen op -o/-a',
    'Sommige woorden houden zich niet aan de vuistregel. Leer ze met lidwoord:',
    ex('<i><b>el</b> problema</i> (op -a, toch mannelijk)', '<i><b>la</b> foto</i> (op -o, toch vrouwelijk)', '<i><b>la</b> ciudad</i>, <i><b>la</b> calle</i>, <i><b>el</b> hotel</i>')),
'a1-u2-l3': card('Meervoud: los en las',
    'In het meervoud wordt <b>el → los</b> en <b>la → las</b>.',
    'Eindigt het woord op een klinker, dan komt er <b>-s</b> achter: <i>la manzana → las manzanas</i>. Op een medeklinker: <b>-es</b>: <i>la flor → las flores</i>.'),
'a1-u2-l4': card('Un, una en hay',
    '"Een" is <b>un</b> (mannelijk) of <b>una</b> (vrouwelijk): <i>un bolso</i>, <i>una nevera</i>.',
    '<b>Hay</b> betekent "er is" én "er zijn": <i>Hay un libro. Hay dos libros.</i>',
    'Let op: <i><b>el</b> agua</i> is vrouwelijk, maar krijgt <i>el</i> omdat het met een beklemtoonde a begint (dat klinkt beter).'),
'a1-u3-l2': card('Nationaliteiten',
    'Nationaliteiten schrijf je <b>zonder hoofdletter</b> en ze passen zich aan aan man/vrouw:',
    ex('<i>holandés → holandesa</i>', '<i>español → española</i>', '<i>americano → americana</i>'),
    'Op <b>-e</b> blijft hetzelfde: <i>Él es belga. Ella es belga.</i> Landen krijgen wél een hoofdletter: <i>Holanda</i>.'),
'a1-u3-l3': card('Werkwoorden op -ir: vivir',
    'Regelmatige werkwoorden op <b>-ir</b> krijgen deze uitgangen:',
    ex('viv<b>o</b> — ik woon', 'viv<b>es</b> — jij woont', 'viv<b>e</b> — hij/zij woont, u woont', 'viv<b>imos</b> — wij wonen', 'viv<b>ís</b> — jullie wonen', 'viv<b>en</b> — zij wonen'),
    '<i>Vivo <b>en</b> Ámsterdam</i>: wonen <b>in</b> een plaats is altijd <b>en</b>.'),
'a1-u4-l1': card('Werkwoorden op -ar: trabajar',
    'De grootste groep werkwoorden eindigt op <b>-ar</b>. Haal -ar eraf en plak de uitgang erachter:',
    ex('trabaj<b>o</b> — ik werk', 'trabaj<b>as</b> — jij werkt', 'trabaj<b>a</b> — hij/zij werkt, u werkt', 'trabaj<b>amos</b> — wij werken', 'trabaj<b>áis</b> — jullie werken', 'trabaj<b>an</b> — zij werken'),
    'Zo gaat het ook met <i>estudiar</i>: <i>estudio, estudias, estudia...</i>'),
'a1-u4-l2': card('Beroep: zonder un/una',
    'Zeg je wát iemand is (beroep), dan gebruik je <b>ser</b> en laat je <b>un/una weg</b>:',
    ex('<i>Soy médico.</i> — Ik ben arts.', '<i>Ella es estudiante.</i> — Zij is student.'),
    'Dus niet <i><s>Soy un médico</s></i>. Het beroep past zich aan: <i>el médico / la médica</i>, <i>el profesor / la profesora</i>.'),
'a1-u5-l1': card('Getallen en hay',
    '<b>Uno</b> wordt <b>un</b> vóór een mannelijk woord en <b>una</b> vóór een vrouwelijk woord: <i>un libro, una mesa</i>.',
    '"Er zijn twee boeken" = <i><b>Hay</b> dos libros.</i> Hay verandert nooit.',
    '"Mijn nummer is vier" = <i>Mi número es cuatro.</i>'),
'a1-u5-l3': card('Leeftijd: tener, niet ser',
    'In het Spaans <b>heb</b> je jaren in plaats van dat je ze <b>bent</b>:',
    ex('<i>Tengo veinte años.</i> — Ik ben twintig (jaar).', '<i>¿Cuántos años tienes?</i> — Hoe oud ben je?'),
    'Dus niet <i><s>Soy veinte</s></i>. Is "años" al gezegd, dan mag je het weglaten: <i>Tengo veinte años, ¿y tú, cuántos tienes?</i>'),
'a1-u5-l4': card('Tener — hebben',
    '<i>Tener</i> is onregelmatig. Let op de <b>ie</b> in tienes, tiene, tienen:',
    ex('<b>tengo</b> — ik heb', '<b>tienes</b> — jij hebt', '<b>tiene</b> — hij/zij heeft, u heeft', 'tenemos — wij hebben', 'tenéis — jullie hebben', '<b>tienen</b> — zij hebben'),
    'Honger en dorst "heb" je ook: <i>Tengo hambre. Tengo sed.</i>'),
'a1-u6-l1': card('Familie: meervoud voor gemengde groepen',
    'Het mannelijk meervoud geldt ook voor een groep met mannen én vrouwen:',
    ex('<i>los padres</i> — de ouders', '<i>los hermanos</i> — de broers en zussen (of de broers)', '<i>los tíos</i> — oom en tante'),
    '<i>Tengo dos hermanos</i> kan dus ook betekenen: een broer en een zus.'),
'a1-u6-l2': card('De persoonlijke a',
    'Is het lijdend voorwerp een <b>persoon</b> (of huisdier), dan zet je er <b>a</b> voor. Die a vertaal je niet:',
    ex('<i>Ayudo <b>a</b> mi abuelo.</i> — Ik help mijn opa.', '<i>Cuido <b>a</b> mi hermana.</i> — Ik pas op mijn zus.', '<i>Quiero <b>a</b> mi familia.</i> — Ik hou van mijn familie.'),
    'Bij dingen geen a: <i>Ayudo en casa. Busco las llaves.</i>'),
'a1-u6-l4': card('Querer: willen of houden van',
    '<i>Querer</i> heeft twee betekenissen:',
    ex('<i>Quiero un café.</i> — Ik wil een koffie.', '<i>Quiero <b>a</b> mi madre.</i> — Ik hou van mijn moeder.'),
    'Bij personen staat de persoonlijke <b>a</b>, en dan betekent het "houden van". Let op de <b>ie</b>: <i>quiero, quieres, quiere, queremos, queréis, quieren</i>.'),
'a1-u7-l1': card('Mi en tu',
    '<b>Mi</b> (mijn) en <b>tu</b> (jouw) krijgen een <b>-s</b> als het bezit meervoud is:',
    ex('<i>mi casa → mis casas</i>', '<i>tu libro → tus libros</i>'),
    '<i>Tu</i> (jouw) heeft geen accent. <i>Tú</i> met accent betekent "jij".'),
'a1-u7-l2': card('Su en nuestro',
    '<b>Su</b> kan betekenen: zijn, haar, uw of hun. Uit de zin blijkt wie bedoeld wordt: <i>Ana vive con su madre</i> = met háár moeder.',
    '<b>Nuestro</b> (ons/onze) past zich aan het bezit aan: <i>nuestr<b>o</b> barrio</i>, <i>nuestr<b>a</b> casa</i>, <i>nuestr<b>os</b> amigos</i>.'),
'a1-u7-l4': card('Van wie is het? — de',
    'Spaans heeft geen \'s. Je zegt "het ... van ...":',
    ex('<i>el lápiz <b>de</b> mi hermana</i> — het potlood van mijn zus', '<i>¿<b>De</b> quién es?</i> — Van wie is het?', '<i>Es <b>de</b> Carlos.</i> — Het is van Carlos.')),
'a1-u8-l1': card('Bijvoeglijke naamwoorden',
    'Een bijvoeglijk naamwoord past zich aan aan man/vrouw en enkelvoud/meervoud:',
    ex('<i>Mi hermano es alt<b>o</b>. Mi hermana es alt<b>a</b>.</i>', '<i>Los chicos son alt<b>os</b>.</i>'),
    'Op <b>-e</b> of een medeklinker blijft het voor man en vrouw gelijk: <i>joven, amable</i>. Meestal staat het <b>achter</b> het zelfstandig naamwoord: <i>un chico alto</i>.'),
'a1-u8-l3': card('Uiterlijk: tener + el pelo',
    'Haar en ogen "heb" je, met lidwoord erbij:',
    ex('<i>Tiene <b>el</b> pelo rubio.</i> — Hij/zij heeft blond haar.', '<i>Tiene <b>los</b> ojos azules.</i> — Hij/zij heeft blauwe ogen.'),
    'Iemand zelf beschrijven gaat met <b>ser</b>: <i>Mi madre es morena.</i>'),
'a1-u9-l1': card('Het weer: hace',
    'Voor veel soorten weer gebruik je <b>hace</b> (letterlijk: "het maakt"):',
    ex('<i>Hace sol / calor / frío / buen tiempo.</i>', '<i>¿Qué tiempo hace?</i> — Wat voor weer is het?'),
    'Regen en sneeuw zijn gewoon werkwoorden: <i>llueve</i> (het regent), <i>nieva</i> (het sneeuwt).'),
'a1-u9-l4': card('Gustar — iets bevalt je',
    '<i>Me gusta</i> betekent letterlijk "het bevalt mij". Het werkwoord hoort bij <b>het ding</b>, niet bij jou:',
    ex('<i>Me gust<b>a</b> el verano.</i> — één ding', '<i>Me gust<b>an</b> las flores.</i> — meer dingen', '<i>Me gusta bailar.</i> — een activiteit: altijd gusta'),
    'Wie het leuk vindt, zie je aan het woordje vooraan: <b>me, te, le, nos, os, les</b>.'),
'a1-u10-l4': card('Werkwoorden op -er: comer',
    'Regelmatige werkwoorden op <b>-er</b> krijgen deze uitgangen:',
    ex('com<b>o</b> — ik eet', 'com<b>es</b> — jij eet', 'com<b>e</b> — hij/zij eet, u eet', 'com<b>emos</b> — wij eten', 'com<b>éis</b> — jullie eten', 'com<b>en</b> — zij eten'),
    'Zo gaat <i>beber</i> ook: <i>bebo, bebes, bebe...</i>'),
'a1-u11-l2': card('Waar is...? — estar',
    'Voor de <b>plek</b> waar iets of iemand is, gebruik je altijd <b>estar</b>:',
    ex('<i>¿Dónde <b>está</b> el banco?</i> — Waar is de bank?', '<i>El banco <b>está</b> a la derecha.</i>')),
'a1-u11-l3': card('Del en al',
    '<b>de + el</b> wordt <b>del</b>, en <b>a + el</b> wordt <b>al</b>:',
    ex('<i>cerca <b>del</b> parque</i> (niet <s>de el</s>)', '<i>al lado <b>del</b> banco</i>', '<i>Voy <b>al</b> centro.</i>'),
    'Met <i>la</i> verandert er niks: <i>cerca de la plaza</i>.'),
'a1-u11-l4': card('Estar — zijn (plek en toestand)',
    '<i>Estar</i> is onregelmatig. Let op de accenten:',
    ex('estoy — ik ben', 'est<b>á</b>s — jij bent', 'est<b>á</b> — hij/zij is, u bent', 'estamos — wij zijn', 'estáis — jullie zijn', 'est<b>á</b>n — zij zijn')),
'a1-u12-l1': card('Ser of estar?',
    'Spaans heeft twee werkwoorden voor "zijn":',
    '<b>ser</b> = wat iemand/iets <b>is</b>: beroep, afkomst, karakter. <i>Soy médico. Soy de Holanda.</i>',
    '<b>estar</b> = <b>waar</b> iets is en <b>hoe</b> het nu gaat: <i>Estoy en casa. Estoy contento.</i>'),
'a1-u12-l2': card('Ser of estar: karakter of gevoel',
    'Hetzelfde woord kan met allebei, maar de betekenis verschilt:',
    ex('<i>Es aburrido.</i> — Hij is saai (karakter).', '<i>Está aburrido.</i> — Hij verveelt zich (nu).'),
    'Ziek, moe en blij-op-dit-moment gaan met <b>estar</b>: <i>Estoy cansado. Está enfermo.</i>'),
'a1-u13-l1': card('Hay of está?',
    '<b>Hay</b> = er is/er zijn (iets nieuws, met <i>un/una</i>, een getal of niks): <i>Hay una mesa en la cocina.</i>',
    '<b>Está</b> = waar een bekend ding is (met <i>el/la</i>): <i>La mesa está en la cocina.</i>'),
'a1-u14-l1': card('Hoe laat is het?',
    'Eén uur is enkelvoud, de rest meervoud:',
    ex('<i><b>Es la</b> una.</i> — Het is één uur.', '<i><b>Son las</b> dos.</i> — Het is twee uur.', '<i>Son las tres <b>y media</b>.</i> — Het is half vier.'),
    'Let op: <i>y media</i> = het uur <b>plus</b> een half uur. "Half vier" is dus <i>las tres y media</i>.'),
'a1-u14-l2': card('Kwart over, kwart voor',
    ex('<i>Son las cuatro <b>y cuarto</b>.</i> — kwart over vier', '<i>Son las cinco <b>menos cuarto</b>.</i> — kwart voor vijf', '<i>Son las dos <b>y diez</b>.</i> — tien over twee'),
    '"Om" een tijd is <b>a</b>: <i>¿<b>A</b> qué hora? — <b>A</b> las ocho.</i>'),
'a1-u15-l1': card('Dagen van de week',
    'Dagen en maanden schrijf je <b>zonder hoofdletter</b>: <i>lunes, martes...</i>',
    ex('<i><b>el</b> lunes</i> — (op) maandag', '<i><b>los</b> lunes</i> — elke maandag'),
    'Je zegt dus geen "en" ervoor: <i>El sábado voy a la playa.</i>'),
'a1-u15-l3': card('De datum',
    'Bij een datum gebruik je <b>el</b> + getal + <b>de</b> + maand:',
    ex('<i>Hoy es <b>el</b> cinco <b>de</b> octubre.</i>', '<i>Mi cumpleaños es <b>el</b> doce <b>de</b> noviembre.</i>'),
    'De eerste van de maand mag <i>el uno</i> of <i>el primero</i> zijn.'),
'a1-u15-l4': card('Ir — gaan',
    '<i>Ir</i> is helemaal onregelmatig:',
    ex('voy — ik ga', 'vas — jij gaat', 'va — hij/zij gaat, u gaat', 'vamos — wij gaan', 'vais — jullie gaan', 'van — zij gaan'),
    '"Naar" is <b>a</b>, en a + el = <b>al</b>: <i>Voy a la playa. Voy al cine.</i>'),
'a1-u16-l1': card('Wederkerende werkwoorden',
    'Werkwoorden op <b>-se</b> doe je "met jezelf". Het -se wordt <b>me, te, se, nos, os, se</b> en komt vóór het werkwoord:',
    ex('<i>despertarse → <b>me</b> despierto</i> — ik word wakker', '<i>¿A qué hora <b>te</b> despiertas?</i>'),
    'Let op: bij <i>despertarse</i> wordt de e een <b>ie</b> (behalve bij wij en jullie): <i>me despierto, nos despertamos</i>.'),
'a1-u16-l3': card('Stamwisseling o → ue',
    'Bij sommige werkwoorden wordt de <b>o</b> een <b>ue</b> (behalve bij wij en jullie):',
    ex('<i>dormir → d<b>ue</b>rmo, d<b>ue</b>rmes, dormimos</i>', '<i>acostarse → me ac<b>ue</b>sto, nos acostamos</i>')),
'a1-u17-l1': card('Jugar al + sport',
    'Een spel of sport spelen = <b>jugar a</b>, en a + el = <b>al</b>:',
    ex('<i>Juego <b>al</b> fútbol.</i>', '<i>Juegas <b>al</b> tenis.</i>'),
    'Bij <i>jugar</i> wordt de u een <b>ue</b>: <i>j<b>ue</b>go, j<b>ue</b>gas, j<b>ue</b>ga, jugamos, jugáis, j<b>ue</b>gan</i>.'),
'a1-u18-l1': card('Deze: este, esta, estos, estas',
    '"Deze/dit" past zich aan:',
    ex('<i><b>este</b> pantalón</i> (mannelijk)', '<i><b>esta</b> camiseta</i> (vrouwelijk)', '<i><b>estos</b> zapatos</i> / <i><b>estas</b> botas</i> (meervoud)')),
'a1-u18-l2': card('Wat kost het?',
    'Het werkwoord hoort bij wat er kost: één ding of meer dingen:',
    ex('<i>¿Cuánto <b>cuesta</b> la camiseta?</i>', '<i>¿Cuánto <b>cuestan</b> los zapatos?</i>')),
'a1-u19-l2': card('Bestellen',
    'Zo bestel je beleefd in een restaurant:',
    ex('<i><b>Para mí</b>, la sopa.</i> — Voor mij de soep.', '<i><b>De primero</b>, ensalada; <b>de segundo</b>, pescado.</i>', '<i>¿<b>Me trae</b> agua, por favor?</i> — Kunt u me water brengen?'),
    '<i>Para mí</i> heeft een accent (mí = mij), anders dan <i>mi</i> (mijn).'),
'a1-u21-l1': card('Pijn: me duele',
    '<i>Doler</i> werkt net als <i>gustar</i>: het werkwoord hoort bij het lichaamsdeel:',
    ex('<i>Me <b>duele</b> la cabeza.</i> — Ik heb hoofdpijn.', '<i>Me <b>duelen</b> los pies.</i> — Mijn voeten doen pijn.'),
    'Je zegt <i>la</i> cabeza, niet <i>mi</i> cabeza: aan <b>me</b> zie je al dat het om jou gaat.'),
'a1-u22-l2': card('Toekomst: ir a + infinitief',
    'Wat je <b>gaat</b> doen zeg je met een vorm van <b>ir</b> + <b>a</b> + het hele werkwoord:',
    ex('<i><b>Voy a</b> viajar.</i> — Ik ga reizen.', '<i>¿<b>Vas a</b> estudiar esta noche?</i>', '<i><b>Va a</b> llover.</i> — Het gaat regenen.'),
    'Vergeet de <b>a</b> niet: <i><s>Voy viajar</s></i> is fout.'),
'a1-u22-l4': card('Moeten: tener que',
    '"Moeten" = <b>tener que</b> + het hele werkwoord:',
    ex('<i><b>Tengo que</b> trabajar.</i> — Ik moet werken.', '<i>¿<b>Tienes que</b> estudiar?</i>')),
'a1-u23-l1': card('Voltooide tijd: he comido',
    'Wat je (vandaag, ooit) <b>gedaan hebt</b> maak je met een vorm van <b>haber</b> + voltooid deelwoord:',
    ex('he — ik heb', 'has — jij hebt', 'ha — hij/zij heeft', 'hemos, habéis, han'),
    'Deelwoord: <b>-ar → -ado</b> (<i>hablado</i>), <b>-er/-ir → -ido</b> (<i>comido, vivido</i>). <i>Ya <b>he comido</b>.</i> — Ik heb al gegeten.'),
'a1-u23-l2': card('Onregelmatige deelwoorden',
    'Deze moet je uit je hoofd leren:',
    ex('<i>hacer → hecho</i> — doen/maken', '<i>ver → visto</i> — zien', '<i>decir → dicho</i> — zeggen', '<i>escribir → escrito</i> — schrijven', '<i>poner → puesto</i> — zetten/leggen', '<i>volver → vuelto</i> — terugkomen', '<i>abrir → abierto</i> — openen', '<i>romper → roto</i> — breken'),
    '<i>Ir</i> is gewoon regelmatig: <i>he ido</i>.'),
}

def apply(intros, path):
    c = open(path, encoding='utf-8').read()
    done = 0
    for lid, html in intros.items():
        assert '`' not in html and '${' not in html, lid
        m = re.search(r"\{ id:['\"]" + re.escape(lid) + r"['\"], kind:'new', ", c)
        assert m, lid
        head = c[m.start():m.start() + 300]
        if 'intro:`' in head.split('words:')[0]:
            continue
        c = c[:m.end()] + 'intro:`' + html + '`, ' + c[m.end():]
        done += 1
    open(path, 'w', encoding='utf-8').write(c)
    print(done, 'intros toegevoegd')

if __name__ == '__main__':
    apply(INTROS, sys.argv[1] if len(sys.argv) > 1 else 'index.html')
