# Voegt grammatica-uitleg (intro) toe aan A2-lessen in index.html.
# Gebruik: python3 dev/a2_intros.py   (idempotent)
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from a1_intros import card, ex, apply

INTROS = {
'a2-u1-l3': card('Me lavo las manos',
    'Bij lichaamsdelen en kleding gebruik je in het Spaans <b>el/la/los/las</b>, niet mijn/jouw. Het wederkerende woordje laat al zien van wie het is:',
    ex('<i>Me cepillo <b>los</b> dientes.</i> — Ik poets mijn tanden.', '<i>Me lavo <b>la</b> cara.</i> — Ik was mijn gezicht.'),
    'Dus niet <i><s>me cepillo mis dientes</s></i>.'),
'a2-u3-l4': card('Divertirse: e → ie',
    '<i>Divertirse</i> (plezier hebben) is wederkerend én de e wordt <b>ie</b> (behalve bij wij en jullie):',
    ex('me div<b>ie</b>rto', 'te div<b>ie</b>rtes', 'se div<b>ie</b>rte', 'nos divertimos', 'os divertís', 'se div<b>ie</b>rten'),
    '<i>Aburrirse</i> (zich vervelen) is gewoon regelmatig: <i>me aburro, te aburres...</i>'),
'a2-u4-l1': card('Afspreken: quedar',
    '<b>Quedar con</b> iemand = met iemand afspreken: <i>Quedo con Ana a las cinco.</i>',
    '<b>¿Te viene bien?</b> (Komt het je uit?) werkt net als <i>gustar</i>: het werkwoord hoort bij de tijd of het plan.',
    ex('<i>¿Te viene bien el lunes?</i>', '<i>Sí, <b>me viene</b> bien.</i>')),
'a2-u5-l4': card('Het weer van vroeger: hacía',
    'Beschrijf je hoe het weer <b>was</b>, dan gebruik je de imperfecto (de "beschrijvende" verleden tijd):',
    ex('<i>hace frío → <b>hacía</b> frío</i>', '<i>llueve → <b>llovía</b></i>', '<i>nieva → <b>nevaba</b></i>', '<i>está nublado → <b>estaba</b> nublado</i>'),
    'Later in A2 leer je deze tijd uitgebreid.'),
'a2-u6-l2': card('Verleden tijd: ganó',
    'Voor een <b>afgeronde gebeurtenis</b> in het verleden gebruik je de <b>pretérito indefinido</b>: <i>Mi equipo <b>ganó</b> el partido.</i>',
    '<b>-ar</b>: gan<b>é</b>, gan<b>aste</b>, gan<b>ó</b>, gan<b>amos</b>, gan<b>asteis</b>, gan<b>aron</b>',
    '<b>-er/-ir</b>: perd<b>í</b>, perd<b>iste</b>, perd<b>ió</b>, perd<b>imos</b>, perd<b>isteis</b>, perd<b>ieron</b>',
    'Let op de accenten: <i>gané</i> (ik won) is iets anders dan <i>gane</i>.'),
'a2-u7-l2': card('Gebiedende wijs (tú)',
    'Iemand de weg wijzen doe je met de gebiedende wijs. Voor <b>tú</b> is dat dezelfde vorm als hij/zij in de tegenwoordige tijd:',
    ex('<i>cruzar → <b>cruza</b> la calle</i> — steek de straat over', '<i>seguir → <b>sigue</b> recto</i> — ga rechtdoor', '<i>girar → <b>gira</b> a la derecha</i> — sla rechtsaf'),
    'Een paar zijn onregelmatig: <i>ir → <b>ve</b></i>, <i>venir → <b>ven</b></i>, <i>hacer → <b>haz</b></i>, <i>poner → <b>pon</b></i>.'),
'a2-u9-l4': card('Conocer of saber?',
    'Allebei "kennen/weten", maar anders gebruikt:',
    '<b>conocer</b> = bekend zijn met een persoon, plek of ding: <i>Conozco Madrid. Conozco <b>a</b> Ana.</i>',
    '<b>saber</b> = een feit weten, of iets kunnen: <i>Sé dónde está. Sé nadar.</i>',
    'Let op: <i>conocer → <b>conozco</b></i> en <i>saber → <b>sé</b></i> (ik-vorm onregelmatig).'),
'a2-u10-l1': card('Por of para?',
    'Allebei vaak "voor", maar met een ander idee:',
    '<b>por</b> = <b>door/via/langs</b>, de weg die je aflegt: <i>Camino <b>por</b> la ciudad. Paseo <b>por</b> el parque.</i>',
    '<b>para</b> = <b>voor</b> iemand, of een doel: <i>Es <b>para</b> ti. <b>Para</b> mí, un café.</i>'),
'a2-u10-l2': card('Waarom en waarvoor',
    ex('<i>¿<b>Por qué</b>?</i> — Waarom? (reden)', '<i><b>Porque</b>...</i> — Omdat... (één woord, geen accent)', '<i>¿<b>Para qué</b>?</i> — Waarvoor? (doel)'),
    '<b>por</b> = de reden: <i>por eso, por amor, por trabajo</i>.',
    '<b>para</b> = het doel, + werkwoord "om te": <i>Estudio <b>para</b> aprender.</i>'),
'a2-u10-l3': card('Por en para bij tijd',
    '<b>por</b> = hoe lang, of een deel van de dag: <i>por dos horas, por la mañana, por la noche</i>.',
    '<b>para</b> = een deadline, vóór wanneer: <i>Es para mañana. Para el lunes.</i>'),
'a2-u10-l4': card('Por: middel en ruil — para: bestemming',
    '<b>por</b> = <b>hoe</b> (middel): <i>por teléfono, por correo, por avión</i>. En bij bedanken: <i>gracias <b>por</b> todo</i>.',
    '<b>para</b> = <b>waarheen</b>: <i>el tren <b>para</b> Madrid</i>.'),
'a2-u14-l1': card('Meer of minder dan',
    ex('<i><b>más</b> grande <b>que</b></i> — groter dan', '<i><b>menos</b> caro <b>que</b></i> — minder duur dan'),
    'Het bijvoeglijk naamwoord past zich aan: <i>La casa es más grand<b>e</b>. Las casas son más grand<b>es</b>.</i>',
    'Bij een getal gebruik je <b>de</b>: <i>más <b>de</b> cien personas</i>.'),
'a2-u14-l2': card('Even ... als',
    '<b>tan</b> + bijvoeglijk naamwoord + <b>como</b>: <i>Es <b>tan</b> bonito <b>como</b> el otro.</i>',
    '<b>tanto/tanta/tantos/tantas</b> + zelfstandig naamwoord + <b>como</b>: <i>Tengo <b>tantos</b> libros <b>como</b> tú.</i>',
    'Na een werkwoord: <b>tanto como</b>: <i>Trabajo <b>tanto como</b> tú.</i>'),
'a2-u14-l3': card('De mooiste: el más ... de',
    '<b>el/la/los/las</b> + <b>más</b> + bijvoeglijk naamwoord + <b>de</b>:',
    ex('<i>Es <b>la</b> ciudad <b>más</b> bonita <b>de</b> España.</i>', '<i>Es <b>el</b> hotel <b>más</b> caro <b>de</b> todos.</i>'),
    'Let op: "van/in" is hier <b>de</b>, niet <i>en</i>.'),
'a2-u14-l4': card('Beter, slechter, ouder, jonger',
    'Deze vergelijkingen zijn onregelmatig: je zegt dus niet <i><s>más bueno</s></i>:',
    ex('<i>bueno → <b>mejor</b></i> — beter', '<i>malo → <b>peor</b></i> — slechter', '<i><b>mayor</b></i> — ouder', '<i><b>menor</b></i> — jonger')),
'a2-u15-l1': card('Past het? — quedar',
    '<i>Quedar</i> werkt hier als <i>gustar</i>: het werkwoord hoort bij de kleding:',
    ex('<i>La camisa <b>me queda</b> bien.</i> — Het overhemd staat me goed.', '<i>Los zapatos <b>me quedan</b> grandes.</i> — De schoenen zijn me te groot.')),
'a2-u15-l3': card('Stof en patroon',
    'Waarvan iets gemaakt is: <b>de</b>: <i>una camisa <b>de</b> algodón, un jersey <b>de</b> lana</i>.',
    'Een patroon: <b>a</b>: <i>una camisa <b>a</b> rayas</i> (gestreept), <i><b>a</b> cuadros</i> (geruit).'),
'a2-u15-l4': card('Probarse: o → ue',
    'Iets passen = <b>probarse</b>. De o wordt <b>ue</b> (behalve bij wij en jullie):',
    ex('me pr<b>ue</b>bo, te pr<b>ue</b>bas, se pr<b>ue</b>ba', 'nos probamos, os probáis, se pr<b>ue</b>ban'),
    'In de verleden tijd blijft het een o: <i>me probé, te probaste</i>.'),
'a2-u16-l1': card('Het: lo en la',
    'Om een ding of persoon niet te herhalen gebruik je <b>lo</b> (mannelijk) of <b>la</b> (vrouwelijk). Het staat <b>vóór</b> het werkwoord:',
    ex('<i>¿Quieres el libro? — Sí, <b>lo</b> quiero.</i>', '<i>¿Llamas a Ana? — Sí, <b>la</b> llamo.</i>'),
    'Bij een heel werkwoord mag het er ook achter vast: <i>Quiero comprar<b>lo</b>.</i>'),
'a2-u16-l2': card('Meervoud: los en las',
    'Meer dingen of personen: <b>los</b> (mannelijk/gemengd) of <b>las</b> (vrouwelijk):',
    ex('<i>¿Tienes los billetes? — Sí, <b>los</b> tengo.</i>', '<i>¿Ves las flores? — Sí, <b>las</b> veo.</i>')),
'a2-u16-l3': card('Aan hem/haar: le en les',
    '<b>le</b> = aan hem/haar/u, <b>les</b> = aan hen. Je gebruikt het bij geven, zeggen, schrijven, vragen...:',
    ex('<i><b>Le</b> doy un regalo a mi madre.</i> — Ik geef mijn moeder een cadeau.', '<i><b>Les</b> escribo una carta.</i> — Ik schrijf hun een brief.'),
    'Het is normaal dat <i>le</i> én <i>a mi madre</i> er allebei staan.'),
'a2-u16-l4': card('Twee tegelijk: me lo, se lo',
    'Staan er twee van deze woordjes, dan komt "aan wie" eerst en "wat" daarna: <i><b>Me lo</b> das.</i> — Je geeft het (aan) mij.',
    'Komen <b>le/les</b> en <b>lo/la/los/las</b> samen, dan wordt le/les <b>se</b>:',
    ex('<i><s>le lo doy</s></i> → <i><b>se lo</b> doy</i> — ik geef het aan hem/haar')),
'a2-u17-l3': card('Hoeveelheden: de',
    'Na een hoeveelheid komt <b>de</b>, zonder lidwoord:',
    ex('<i>un litro <b>de</b> leche</i>', '<i>medio kilo <b>de</b> tomates</i>', '<i>una docena <b>de</b> huevos</i>', '<i>un trozo <b>de</b> queso</i>'),
    'Let op: "een halve kilo" is <i>medio kilo</i>, zonder <i>un</i>.'),
'a2-u21-l4': card('Nodig hebben: hace falta',
    '<b>Hacer falta</b> werkt als <i>gustar</i>: het werkwoord hoort bij wat je nodig hebt:',
    ex('<i><b>Me hace falta</b> un carpintero.</i> — Ik heb een timmerman nodig.', '<i><b>Me hacen falta</b> dos sillas.</i> — Ik heb twee stoelen nodig.'),
    'Hetzelfde kan ook met <i>necesitar</i>: <i>Necesito un carpintero.</i>'),
'a2-u26-l4': card('Sentirse: e → ie',
    '<i>Sentirse</i> (zich voelen):',
    ex('me s<b>ie</b>nto, te s<b>ie</b>ntes, se s<b>ie</b>nte', 'nos sentimos, os sentís, se s<b>ie</b>nten'),
    'In de verleden tijd: <i>me sentí, te sentiste, se <b>sintió</b></i>.'),
'a2-u28-l1': card('Ervaringen: he estado',
    'De voltooide tijd (haber + deelwoord) gebruik je voor wat je <b>ooit</b> of <b>tot nu toe</b> gedaan hebt:',
    ex('<i><b>Ya</b> he estado en Madrid.</i> — Ik ben al in Madrid geweest.', '<i><b>Todavía no</b> he probado la paella.</i> — Ik heb nog geen paella geproefd.'),
    'Tussen <i>he</i> en het deelwoord komt niks: <i>no lo he visto</i>.'),
'a2-u28-l3': card('Net gedaan: acabar de',
    '<b>acabar de</b> + heel werkwoord = iets <b>net</b> gedaan hebben: <i>Acabo de comer.</i> — Ik heb net gegeten.',
    'Met <b>este/esta/hoy</b> gebruik je in Spanje de voltooide tijd: <i>Este otoño <b>ha llovido</b> mucho.</i>',
    'In Latijns-Amerika hoor je daar vaak de gewone verleden tijd: <i>Este otoño llovió mucho.</i> Allebei goed.'),
'a2-u29-l1': card('Meer onregelmatige deelwoorden',
    'Herhaling en nieuwe:',
    ex('<i>hacer → hecho, decir → dicho, ver → visto, poner → puesto</i>', '<i>freír → frito, imprimir → impreso</i>', '<i>devolver → devuelto, deshacer → deshecho</i>'),
    'Samengestelde werkwoorden volgen het basiswerkwoord: <i>volver → vuelto</i>, dus <i>devolver → devuelto</i>.'),
'a2-u29-l2': card('Deelwoord als bijvoeglijk naamwoord',
    'Een deelwoord kan ook een bijvoeglijk naamwoord zijn. Dan past het zich aan:',
    ex('<i>La puerta está <b>abierta</b>.</i>', '<i>Los vasos están <b>rotos</b>.</i>'),
    'Na <b>haber</b> verandert het nooit: <i>Ella ha abierto la puerta.</i>'),
'a2-u32-l1': card('Vroeger: de imperfecto',
    'Voor hoe iets <b>was</b> of wat je <b>vroeger altijd</b> deed, gebruik je de imperfecto:',
    '<b>-ar</b>: jug<b>aba</b>, jug<b>abas</b>, jug<b>aba</b>, jug<b>ábamos</b>, jug<b>abais</b>, jug<b>aban</b>',
    '<b>-er/-ir</b>: viv<b>ía</b>, viv<b>ías</b>, viv<b>ía</b>, viv<b>íamos</b>, viv<b>íais</b>, viv<b>ían</b>',
    '<i>Cuando <b>era</b> niño, <b>jugaba</b> en el parque.</i> Er zijn maar drie onregelmatige: <i>ser → era</i>, <i>ir → iba</i>, <i>ver → veía</i>.'),
'a2-u33-l3': card('Niet meer, gewoonlijk, ophouden',
    ex('<i><b>ya no</b></i> — niet meer: <i>Ya no fumo.</i>', '<i><b>soler</b> + werkwoord</i> — gewoonlijk: <i>Suelo leer. Antes solía leer.</i>', '<i><b>dejar de</b> + werkwoord</i> — ophouden met: <i>Dejé de fumar.</i>', '<i><b>empezar a</b> + werkwoord</i> — beginnen met: <i>Empecé a correr.</i>')),
'a2-u33-l4': card('Imperfecto: era, había',
    'De onregelmatige vormen die je het meest hoort:',
    ex('<i>ser → <b>era</b>, eras, era, éramos, erais, eran</i>', '<i>ir → <b>iba</b>, ibas, iba, íbamos, ibais, iban</i>', '<i>haber → <b>había</b></i> — er was/er waren'),
    '<i>Había</i> is de verleden tijd van <i>hay</i>, en verandert ook nooit: <i>Había muchos niños.</i>'),
'a2-u34-l1': card('Levensloop: nació, vivió',
    'Een biografie vertel je in de <b>pretérito indefinido</b>: afgeronde gebeurtenissen.',
    ex('<i>Nac<b>ió</b> en Madrid en 1990.</i>', '<i>Estudi<b>ó</b> en Sevilla.</i>', '<i>Se cas<b>ó</b> a los veinticinco años.</i>'),
    'Hij/zij-vorm: <b>-ar → -ó</b>, <b>-er/-ir → -ió</b>. Jaartallen lees je als gewoon getal: <i>mil novecientos noventa</i>.'),
'a2-u35-l4': card('Onregelmatige verleden tijd',
    'Veel gebruikte werkwoorden zijn onregelmatig in de indefinido (en hebben géén accent):',
    ex('<i>ser / ir → <b>fue</b></i> — was / ging', '<i>tener → <b>tuvo</b></i>', '<i>estar → <b>estuvo</b></i>', '<i>hacer → <b>hizo</b></i>', '<i>poder → <b>pudo</b></i>', '<i>decir → <b>dijo</b></i>'),
    '<i>Tuvo lugar</i> = vond plaats.'),
'a2-u36-l1': card('Indefinido: wat gebeurde er?',
    'De <b>indefinido</b> gebruik je voor iets dat op een bepaald moment gebeurde en <b>klaar</b> is.',
    'Signaalwoorden: <i>ayer, anoche, la semana pasada, el año pasado, hace dos días, en 2020</i>.',
    ex('<i>Ayer <b>fui</b> al cine.</i>', '<i>La semana pasada <b>comí</b> paella.</i>')),
'a2-u36-l2': card('Imperfecto: hoe was het?',
    'De <b>imperfecto</b> gebruik je voor <b>beschrijvingen</b> (tijd, weer, gevoel) en <b>gewoontes</b>.',
    'Signaalwoorden: <i>siempre, todos los días, normalmente, de joven, con frecuencia</i>.',
    ex('<i><b>Era</b> de noche y <b>hacía</b> frío.</i>', '<i>De joven <b>jugaba</b> al fútbol.</i>')),
'a2-u36-l3': card('Samen: mientras en cuando',
    'Wat <b>bezig was</b> staat in de imperfecto, wat er <b>tussendoor gebeurde</b> in de indefinido:',
    ex('<i>Mientras <b>caminaba</b>, <b>empezó</b> a llover.</i>', '<i><b>Estaba</b> durmiendo cuando <b>sonó</b> el teléfono.</i>'),
    'Zie het als een film: de imperfecto is het decor, de indefinido de actie.'),
'a2-u36-l4': card('Naast elkaar',
    ex('<i>habl<b>é</b> / habl<b>aba</b></i> — ik sprak (één keer) / ik sprak (vaak)', '<i>com<b>í</b> / com<b>ía</b></i>', '<i><b>fui</b> / <b>iba</b></i> — ging', '<i><b>vi</b> / <b>veía</b></i> — zag'),
    'Twijfel je? Vraag je af: is het een <b>afgerond moment</b> (indefinido) of een <b>beschrijving/gewoonte</b> (imperfecto)?'),
}

if __name__ == '__main__':
    apply(INTROS, sys.argv[1] if len(sys.argv) > 1 else 'index.html')
