# Voegt grammatica-uitleg (intro) toe aan B1/B2-lessen die nieuwe grammatica gebruiken
# zonder dat die eerder is uitgelegd. (De grammatica-units zelf hadden al uitleg.)
# Gebruik: python3 dev/b1b2_intros.py   (idempotent; lessen met een intro worden overgeslagen)
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from a1_intros import card, ex, apply

INTROS = {
# ---------- B1 ----------
'b1-u1-l3': card('Voorproefje: prefiero que...',
    'Wil je dat <b>iemand anders</b> iets doet, dan verandert het werkwoord na <i>que</i> een beetje. Dat heet de <b>subjuntivo</b>:',
    ex('<i>Prefiero que habl<b>emos</b> en español.</i> — Ik heb liever dat we Spaans praten.', '<i>Es importante que practiqu<b>es</b> cada día.</i> — Het is belangrijk dat je elke dag oefent.'),
    'In de volgende les zie je hoe je die vorm maakt, en in unit 3 leer je hem helemaal. <i>Me gustaría que <b>vinieras</b></i> (ik zou willen dat je kwam) gebruikt nog een andere vorm. Onthoud die voor nu als vaste combinatie.'),
'b1-u1-l4': card('De subjuntivo herkennen',
    'De truc: de klinker van de uitgang <b>wisselt om</b>. Bij -ar wordt het een <b>e</b>, bij -er/-ir een <b>a</b>:',
    ex('hablar → habl<b>e</b>, habl<b>es</b>, habl<b>emos</b>', 'comer → com<b>a</b>, com<b>as</b>, com<b>amos</b>', 'vivir → viv<b>a</b>, viv<b>as</b>, viv<b>amos</b>'),
    'Je gebruikt hem na o.a. <i>quiero que</i>, <i>espero que</i>, <i>es importante que</i>: <i>Quiero que <b>hables</b> conmigo.</i>'),
'b1-u2-l4': card('Ser of estar: andere betekenis',
    'Sommige bijvoeglijke naamwoorden betekenen iets anders met <b>ser</b> (hoe iemand/iets is) of <b>estar</b> (hoe het nu is):',
    ex('<i><b>es</b> aburrido</i> — is saai · <i><b>está</b> aburrido</i> — verveelt zich', '<i><b>es</b> listo</i> — is slim · <i><b>está</b> listo</i> — is klaar', '<i><b>es</b> malo</i> — is slecht/gemeen · <i><b>está</b> malo</i> — is ziek', '<i><b>es</b> rico</i> — is rijk · <i><b>está</b> rico</i> — is lekker')),
'b1-u3-l2': card('Stamwissel in de subjuntivo',
    'Werkwoorden met een stamwissel (o → ue, e → ie) houden die ook in de subjuntivo:',
    ex('<i>d<b>ue</b>rmo → d<b>ue</b>rma, d<b>ue</b>rmas</i>', '<i>p<b>ie</b>nso → p<b>ie</b>nse, p<b>ie</b>nses</i>'),
    'Let op bij <b>wij</b>: <i>dormir</i> wordt daar <i>d<b>u</b>rmamos</i>. <i>Es necesario que <b>durmamos</b> temprano.</i>'),
'b1-u3-l4': card('Onregelmatige ik-vorm',
    'Is de <b>yo</b>-vorm onregelmatig, dan bouw je de subjuntivo gewoon daarop:',
    ex('<i>ten<b>go</b> → ten<b>ga</b></i>', '<i>ha<b>go</b> → ha<b>ga</b></i>', '<i>di<b>go</b> → di<b>ga</b></i>', '<i>sal<b>go</b> → sal<b>ga</b></i>'),
    '<i>Espero que <b>tengas</b> suerte.</i> — Ik hoop dat je geluk hebt.'),
'b1-u6-l4': card('Een verzoek in het verleden: que + -ra',
    'Staat het eerste werkwoord in de verleden tijd (<i>rogué, pedí, quería</i>), dan krijgt het tweede een <b>-ra-vorm</b>. Dat is de <b>imperfecto de subjuntivo</b>.',
    'Je maakt hem van de <b>ellos</b>-vorm van de verleden tijd: haal <b>-ron</b> eraf en zet er <b>-ra</b> achter:',
    ex('<i>quedaron → queda<b>ra</b></i>', '<i>perdonaron → perdona<b>ra</b></i>', '<i>fueron → fue<b>ra</b></i>', '<i>tuvieron → tuvie<b>ra</b></i>'),
    '<i>Le rogué que se <b>quedara</b>.</i> — Ik smeekte hem te blijven.'),
'b1-u9-l2': card('Advies met "zou": que + -ra',
    'Geef je advies met een "zou"-vorm (<i>sería, convendría</i>), dan komt er ook een <b>-ra-vorm</b> na <i>que</i>:',
    ex('<i>Convendría que <b>revisaras</b> el contrato.</i> — Het zou goed zijn als je het contract nakeek.', '<i>Sería buena idea que <b>descansaras</b>.</i> — Het zou een goed idee zijn als je wat rustte.'),
    'Vaste combinatie: <i><b>Si yo fuera tú</b>, ...</i> — Als ik jou was, ... De "zou"-vorm zelf (<i>hablaría, sería</i>) leer je in unit 12.'),
'b1-u12-l3': card('Beleefd vragen',
    'Met de condicional klinkt een vraag vriendelijker en minder direct:',
    ex('<i>¿Puedes...? → ¿<b>Podrías</b> cerrar la ventana?</i>', '<i>Quiero... → Me <b>gustaría</b> reservar una mesa.</i>', '<i>¿Te <b>importaría</b> esperar un momento?</i> — Zou je het erg vinden even te wachten?'),
    'Tegen iemand die je met <i>usted</i> aanspreekt: <i>¿Le <b>molestaría</b>...?</i>'),
'b1-u12-l4': card('Advies: yo que tú...',
    'Om advies te geven zet je jezelf in de plaats van de ander, met de condicional:',
    ex('<i><b>Yo que tú</b>, hablaría con ella.</i> — Als ik jou was, zou ik met haar praten.', '<i><b>En tu lugar</b>, aceptaría la oferta.</i> — In jouw plaats zou ik het aanbod accepteren.', '<i>¿Qué <b>harías</b> tú?</i> — Wat zou jij doen?')),
'b1-u15-l2': card('Een oordeel + que + subjuntivo',
    'Geef je een oordeel of reactie (<i>es raro, es normal, es increíble, qué pena</i>), dan volgt de subjuntivo:',
    ex('<i>Es normal que <b>tengas</b> dudas.</i>', '<i>Qué pena que no <b>puedas</b> venir.</i>'),
    'Gaat het over iets dat al gebeurd is, dan gebruik je <b>haya + deelwoord</b> (de subjuntivo van <i>ha terminado</i>):',
    ex('<i>Es increíble que <b>hayas terminado</b> tan rápido.</i> — Ongelooflijk dat je al klaar bent.')),
'b1-u15-l3': card('Creo que of no creo que?',
    'Ben je <b>zeker</b>, dan gewoon de indicativo. <b>Twijfel</b> of ontken je, dan de subjuntivo:',
    ex('<i>Creo que <b>tiene</b> razón.</i> — Ik denk dat hij gelijk heeft.', '<i>No creo que <b>tenga</b> razón.</i> — Ik denk niet dat hij gelijk heeft.'),
    'Ook met indicativo: <i>estoy seguro de que, es verdad que, está claro que, no dudo que</i>.'),
'b1-u22-l2': card('Had gedaan: de pluscuamperfecto',
    'Voor iets dat <b>nog eerder</b> gebeurde dan een ander moment in het verleden: <b>había</b> + deelwoord.',
    ex('había, habías, había, habíamos, habíais, habían + <i>perdido</i>', '<i>Nos dimos cuenta de que <b>habíamos perdido</b> el mapa.</i> — We merkten dat we de kaart kwijt waren geraakt.'),
    'Handig bij het vertellen: <i><b>acabar de</b> + infinitief</i> = net iets gedaan hebben (<i>Acabábamos de llegar.</i>), <i><b>seguir</b> + gerundio</i> = doorgaan met (<i>Seguimos caminando.</i>).'),
'b1-u28-l2': card('Bevelen doorgeven: que + -ra',
    'Geef je een bevel of verzoek door in de verleden tijd, dan komt na <i>que</i> de <b>-ra-vorm</b>:',
    ex('<i>"¡Ven!" → Le dijo que <b>viniera</b>.</i>', '<i>"Espera." → Le pidió que <b>esperara</b>.</i>', '<i>"Ve al médico." → Le recomendó que <b>fuera</b> al médico.</i>'),
    'Weet je het nog? <i>vinieron → vinie<b>ra</b></i>: ellos-vorm van de verleden tijd, <b>-ron</b> eraf, <b>-ra</b> erbij.'),
'b1-u36-l4': card('Iemand die... + subjuntivo',
    'Weet je niet of iemand of iets <b>bestaat</b>, of bestaat het juist niet, dan volgt de subjuntivo:',
    ex('<i>Busco un piso que <b>tenga</b> terraza.</i> — (bestaat het?)', '<i>Tengo un piso que <b>tiene</b> terraza.</i> — (dat heb ik echt)', '<i>No hay nadie que <b>cocine</b> como mi abuela.</i>'),
    'Zo ook: <i>lo que <b>quieras</b>, donde <b>quieras</b>, cuando <b>quieras</b></i> — wat/waar/wanneer je maar wilt.'),
'b1-u38-l4': card('Si fuera..., -ría',
    'Voor een droom of iets dat (nu) niet waar is: <b>si + -ra-vorm</b>, en dan de condicional:',
    ex('<i>Si <b>fuera</b> rica, <b>compraría</b> una casa en la playa.</i> — Als ik rijk was, zou ik een huis aan het strand kopen.', '<i>Si <b>tuviera</b> tiempo, <b>viajaría</b> más.</i>'),
    'In B2 leer je deze als-zinnen helemaal.'),
# ---------- B2 ----------
'b2-u2-l3': card('-ra of -se: allebei goed',
    'De imperfecto de subjuntivo heeft twee vormen die precies hetzelfde betekenen:',
    ex('<i>habla<b>ra</b> = habla<b>se</b></i>', '<i>fue<b>ra</b> = fue<b>se</b></i>', '<i>tuvié<b>ramos</b> = tuvié<b>semos</b></i>'),
    'De -ra-vorm hoor je het meest. Pico rekent ze allebei goed. Let op het accent bij <b>wij</b>: <i>habl<b>á</b>ramos, fu<b>é</b>ramos</i>.'),
'b2-u2-l4': card('Beleefd en voorzichtig',
    '<b>Quisiera</b> is nog beleefder dan <i>me gustaría</i>: <i>Quisiera hablar con el responsable.</i>',
    'Na een "zou"-vorm met <i>que</i> volgt de -ra-vorm:',
    ex('<i>Sería mejor que <b>salierais</b> temprano.</i>', '<i>Preferiría que no me <b>llamaras</b> al trabajo.</i>', '<i>¿Le importaría que <b>abriera</b> la ventana?</i>')),
'b2-u41-l4': card('Lo = "het" of "dat"',
    '<b>Lo</b> kan naar een heel idee verwijzen, niet alleen naar een ding:',
    ex('<i><b>Lo</b> sé.</i> — Ik weet het.', '<i>Dicen que es inteligente, y <b>lo</b> es.</i> — en dat is ze ook.'),
    'Tegen <b>usted</b> gebruik je bij een verzoek de subjuntivo-vorm, met het voornaamwoord erachter of (bij "niet") ervoor:',
    ex('<i><b>Dígamelo.</b></i> — Zegt u het maar.', '<i>No <b>se vaya</b> todavía.</i> — Gaat u nog niet weg.')),
'b2-u31-l4': card('Lo cual, los que, quienquiera',
    '<b>Lo cual</b> verwijst naar de hele zin ervoor (= wat): <i>El tren va con retraso, <b>lo cual</b> significa que...</i>',
    '<b>Los que / la gente que</b> = de mensen die: <i><b>Los que</b> saben de vinos dicen...</i>',
    '<b>Quienquiera que</b> + subjuntivo = wie ook maar: <i>Quienquiera que <b>haya</b> sido, que lo diga.</i>'),
}

if __name__ == '__main__':
    apply(INTROS, sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'index.html'))
